# Generated by Django 3.1 on 2020-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Openml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrixvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=30)),
                ('y', models.CharField(max_length=30)),
            ],
        ),
    ]
