# Generated by Django 3.1 on 2020-08-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Openml', '0002_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='file',
            new_name='myfile',
        ),
    ]
