# Generated by Django 3.1 on 2020-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Openml', '0003_auto_20200908_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixvalue',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matrixvalue',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
