# Generated by Django 3.1 on 2020-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Openml', '0004_auto_20200909_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.CharField(max_length=7)),
                ('y_value', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Matrixvalue',
        ),
    ]
