# Generated by Django 3.1 on 2020-08-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Openml', '0005_auto_20200822_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='name',
        ),
    ]
