# Generated by Django 3.1 on 2020-08-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Openml', '0006_remove_csv_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csv',
        ),
    ]
